scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']